### ISSUE TITLE
Angular 11 build Warning: mat-table-filter\__ivy_ngcc__\fesm2015\mat-table-filter.js depends on 'util'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by hamedsbt** [HalitTalha/ng-material-extensions#101]
I know the developer may prefer use external libs but it may cause trouble such as **Angular 11 build Warning**:
mat-table-filter.js **depends on 'util'**. CommonJS or AMD dependencies can cause optimization bailouts.
mat-table-filter.js **depends on 'lodash'**. CommonJS or AMD dependencies can cause optimization bailouts.

Do you have any plan to provide a solution for more compatibility with modern optimization approach?!

**Comment by HalitTalha** [comment]
xlsx will be handled later.
