### ISSUE TITLE
My problem with properyOptions

### ISSUE THREAD

**Issue by laurentiubl** [HalitTalha/ng-material-extensions#114]
I have a problem with properyOptions, I would like to ask you how I could take my whole object (the whole row) for example: not only the value from "weight".

this.propertyOptions['weight'] = ((exemple) => {

   //here I would like to know how I can have the whole row in "example", not just the value from 'weight'...

       });

Thanks you very much!

**Comment by HalitTalha** [comment]
Hi @laurentiubl,
I guess what you are trying to achieve is best suited for `customPredicate: (data: any) => boolean` property of the mat-table-filter.
Because propertyOptions is to handle special cases for only the properties of the rows.
If I didn't get you right could you please explain a little bit more?

**Comment by laurentiubl** [comment]
I am interested  handling special cases for the "weight" property in my rows, but when I handle I would like to have access to the whole row inside the method.
**For exemple:**
`    this.propertyOptions['weight'] = ((a) => {

     let weightFromMyCurrentRow = a; // in this case 'a' returns my value from "weight" which is very correct and that's what I need, but if I needed for example the id column from the same row in this method, could I?

     let TheOtherColumnsFromMyCurrentRow = a; // here I want to have the other columns if is possible in this method... 
 
    let id = a; // or how I could access the id column when I handle the "weight" property ?
       });`

I hope I understood and thank you very much for the answer!

**Comment by laurentiubl** [comment]
Hello Halit Talha,
thank you for the answer, I also answered your question now, I hope you understand what I meant.


Best regards,


Laurentiu Blaga

On May 16, 2021 at 1:34 PM, Halit Talha TÜRE ***@***.***> wrote:






Hi @laurentiubl,
I guess what you are trying to achieve is best suited for customPredicate: (data: any) => boolean property of the mat-table-filter.
Because propertyOptions is to handle special cases for only the properties of the rows.
If I didn't get you right could you please explain a little bit more?

**Comment by HalitTalha** [comment]
Hi @laurentiubl,

Access to the row is not possible like that since it is for building property specific predicates.

However there is a way to achieve what you require:
You create a customPredicate for the whole filtering and handle your special case along with the filtering of the directive's filterService.
```
<mat-table matTableFilter [exampleEntity]="filterEntity" [customPredicate]="myCustomPredicate "...
```

```
constructor(private filterService: MatTableFilterService)......

this.myCustomPredicate = (item: any): boolean => {
        const filterServiceResult = this.filterService.filterPredicate({ example: this.exampleEntity, item }, this.propertyOptions,
          { filterType: this.filterType, caseSensitive: this.caseSensitive });

        const myCustomWeightPredicateResult = compareIdRelatedStuff(item);

       return myCustomWeightPredicateResult  && filterServiceResult;
      };
```

**Comment by laurentiubl** [comment]
Done✅ thanks you very much!
