### ISSUE TITLE
Update xlsx 0.16.9 to 0.17.0

### ISSUE THREAD

**Issue by SGTMcClain** [HalitTalha/ng-material-extensions#125]
SheetJS (xlsx) 0.16.9 allows attackers to cause a denial of service (CPU_ consumption via a crafted .xlsx document that is mishandled when read by xlsx.js.

SheetJS has fixed this in 0.17.0 however I would like to be sure that the fix doesn't break anything within the cdk-table-exporter

It looks like the bot has already submitted the update in Pull Requests it just needs to be approved

**Comment by aki-kesulahti** [comment]
I would really like to see this update happening because it's causing moderate severity vulnerabilities alerts from npm audit and Dependabot. Too bad this whole project is on one person shoulders.

**Comment by HalitTalha** [comment]
Released the fixed version. Sorry for being able to release every 6 months or so.
