### ISSUE TITLE
Change the filename at runtime

### ISSUE THREAD

**Issue by tonydrake** [HalitTalha/ng-material-extensions#130]
Feeling silly here - trying to change the filename exported at runtime (adding context to the export). I've spent a few hours feeling like it must be easy, but missing something.

Is this something that can be done? Or do I need a nasty nest of options:
eg
```
   <ng-container *ngIf="reportMetaData.reportId == 2">
      <button mat-button color="primary" (click)="exporter.exportTable('xlsx', {fileName:'Maintenance Summary'})" [disabled]="loadingIndicator">Export to Excel</button>
    </ng-container>
```

but I want to do something like this:

`      <button mat-button color="primary" (click)="exporter.exportTable('xlsx', { fileName:'{{reportMetaData.name}}' })" [disabled]="loadingIndicator">Export to Excel</button>
`

**Comment by HalitTalha** [comment]
Hello there,

This should suffice:
`<button mat-button color="primary" (click)="exporter.exportTable('xlsx', {fileName:reportMetaData.name})" [disabled]="loadingIndicator">Export to Excel</button>`
