### ISSUE TITLE
Angular 14 Support

### ISSUE THREAD

**Issue by billyjov** [HalitTalha/ng-material-extensions#155]
Hi, is there any plan to add Angular 14 support? 

Are PRs welcome?

**Comment by sinedoOo** [comment]
Any update here?

**Comment by sinedoOo** [comment]
Is this project dead? Last release almost year ago.

**Comment by DRK-Jingles** [comment]
Made Pull Request to fix extends options error, called Angular14 Support.
https://github.com/HalitTalha/ng-material-extensions/pull/158
Hope it Helps ( ಠ‿<)

**Comment by pantonis** [comment]
Are you planning to update for angular 15?
