### ISSUE TITLE
Support for Angular Material v15

### ISSUE THREAD

**Issue by AndresCarvalloABM** [HalitTalha/ng-material-extensions#171]
Hello

Today, I have finished updating the project from Angular v14 to v15, along with Angular Material to v15.
Once I try to run the application, I get the following error for `cdk-table-exporter`

```
Error: node_modules/cdk-table-exporter/lib/services/exporters/file-exporter.d.ts:3:67 - error TS2344: Type 'T' does not satisfy the constraint 'Options'.

3 export declare abstract class FileExporter<T> implements Exporter<T> {
                                                                    ~

  node_modules/cdk-table-exporter/lib/services/exporters/file-exporter.d.ts:3:44
    3 export declare abstract class FileExporter<T> implements Exporter<T> {
                                                 ~
    This type parameter might need an `extends Options` constraint.
```

<img width="657" alt="image" src="https://user-images.githubusercontent.com/103586910/211918663-00d94f49-990e-46d0-8950-8707094db775.png">

I managed to compile the project using `"skipLibCheck": true` into `tsconfig.json` but once I'm about to export as a CSV file, I run into this error

![image](https://user-images.githubusercontent.com/103586910/211928135-fb735f19-92e1-442d-b95a-d4004cd1752b.png)

**Comment by ianDGM** [comment]
Experiencing the same Issue. Commenting to help visibility.

**Comment by ludovicoloreti** [comment]
same issue here.

**Comment by ianDGM** [comment]
So I was able to get my application running locally by adding this import 

`import { Options } from '../../options';`

and then editing the class declaration to say:

`export declare abstract class FileExporter<T extends Options> implements Exporter<T> {`

But this is changing the node_modules and not sure how viable that is.

**Comment by ludovicoloreti** [comment]
> So I was able to get my application running locally by adding this to file-exporter.d.ts
> 
> 
> 
> `import { Options } from '../../options';`
> 
> 
> 
> and then editing the class declaration to say:
> 
> 
> 
> `export declare abstract class FileExporter<T extends Options> implements Exporter<T> {`
> 
> 
> 
> But this is changing the node_modules and not sure how viable that is.


Can you fork it with the code changes?
In this way it will be possible for everybody to install that version via `npm i`

**Comment by ianDGM** [comment]
> > So I was able to get my application running locally by adding this to file-exporter.d.ts
> > `import { Options } from '../../options';`
> > and then editing the class declaration to say:
> > `export declare abstract class FileExporter<T extends Options> implements Exporter<T> {`
> > But this is changing the node_modules and not sure how viable that is.
> 
> Can you fork it with the code changes? In this way it will be possible for everybody to install that version via `npm i`
> 
> EDIT: Seeing old in comments the author saying "pull requests" are kindly welcome

I made the changes and submitted a pull request.

**Comment by ianDGM** [comment]
> > So I was able to get my application running locally by adding this to file-exporter.d.ts
> > `import { Options } from '../../options';`
> > and then editing the class declaration to say:
> > `export declare abstract class FileExporter<T extends Options> implements Exporter<T> {`
> > But this is changing the node_modules and not sure how viable that is.
> 
> Can you fork it with the code changes? In this way it will be possible for everybody to install that version via `npm i`
> 
> EDIT: Seeing old in comments the author saying "pull requests" are kindly welcome

seems like someone has already made a pull request here. https://github.com/HalitTalha/ng-material-extensions/pull/158/commits

**Comment by joerggross** [comment]
We run into the same problems using Angular 15.
Is there any update/progress on this issue?

**Comment by shajeermhmmd** [comment]
We are also facing the same issue... is there any solution?

**Comment by HalitTalha** [comment]
Hi there,
Since this would require a full rebuild of the Angular workspace with newer versions, it's taking time. But I hope I'll be able to handle it soon. If anyone could have done it before (upgraded the workspace and projects into v15) that would be great to have this as a PR.
