### ISSUE TITLE
paginator error

### ISSUE THREAD

**Issue by Saiprasadsharma** [HalitTalha/ng-material-extensions#174]
Hi, Am new to angular, when I was using mat-table-exporter to export data that had pagination I was getting an error

It was the error am getting
![image](https://user-images.githubusercontent.com/72647965/224247359-af7417b8-f137-44eb-b251-72bed6b8768e.png)

Then I modified the code inside this path
node_modules\mat-table-exporter\__ivy_ngcc__\fesm2015\mat-table-exporter.js

from this
![image](https://user-images.githubusercontent.com/72647965/224247712-df105e5f-a61a-4952-9183-b56372e088d5.png)

 to this
![image](https://user-images.githubusercontent.com/72647965/224247903-2a1cb13d-cbcd-4fb4-95c2-4189cf8d73e7.png)

and the issue got resolved in the local environment but it still persists in the live environment
What should I do to resolve this issue?

**Comment by HalitTalha** [comment]
Hi @Saiprasadsharma ,
This was due to the breaking changes introduced in angular 15.
a new version has been released yesterday for Angular 15 support.
