### ISSUE TITLE
Custom Exporter Error with Angular 14 (error TS2554: Expected 1 arguments, but got 0)

### ISSUE THREAD

**Issue by NA-Jalilius** [HalitTalha/ng-material-extensions#188]
Hello friends, 

Reference to similar problem : #168 

I'm sorry to comment on thus issue but I find it weir that I'm facing the same problem although I'm on the v14.0.2 (using Angular 14) but I get this error (see SS below) when I want to instantiate the custom exporter that extends the CsvExporterService from 'mat-table-exporter' 

This is my custom class :
```
import {Options, CsvExporterService} from 'mat-table-exporter';

export class CustomCsvExporter extends CsvExporterService {

  // Override
  public createContent (rows: Array<any>, options?: Options): any {
    console.error(rows)
    return super.createContent (rows, options);
  }
}
```

And this is the error I get :( :

![image](https://github.com/HalitTalha/ng-material-extensions/assets/41047953/9f2f2e02-76e2-448b-abb1-d8edaee2484f)

The related dependencies in my package.json are 

```
"dependencies": {
    "@angular-material-components/datetime-picker": "^8.0.0",
    "@angular/animations": "^14.2.11",
    "@angular/cdk": "^14.2.7",
    "@angular/common": "^14.2.11",
    "@angular/compiler": "^14.2.11",
    "@angular/core": "^14.2.11",
    "@angular/flex-layout": "^14.0.0-beta.41",
    "@angular/forms": "^14.2.11",
    "@angular/material": "^14.2.7",
    "@angular/material-moment-adapter": "^14.2.7",
    "@angular/platform-browser": "^14.2.11",
    "@angular/platform-browser-dynamic": "^14.2.11",
    "@angular/router": "^14.2.11",
    ...
    "mat-table-exporter": "^14.0.2",
    ...
}
```

Any help is much appreciated and if you need any additional info I'll be happy to provide.

And thank you so much @HalitTalha for the amazing work on these libraries, Very nice work 👍 !

**Comment by shantanugautam1** [comment]
@NA-Jalilius @HalitTalha any update on this? I am facing this issue too. What was the workaround/fix that you used?
I'm on angular 15.

**Comment by NA-Jalilius** [comment]
> @NA-Jalilius @HalitTalha any update on this? I am facing this issue too. What was the workaround/fix that you used? I'm on angular 15.

Hello there !

Actually I didn't find a solution to that error, rather than that, I came up with a work around that did the job for my main purpose, can't say I'll do it for you but I'll share with you the parts of my code that did the job that I wanted to do via the custom exporter without having to go through all of what was suggested to implement this

In my HTML template :

```
<button [disabled]="exporting"
            (click)="exportContentAsCsv(exporter)"
            color="primary"
            mat-mini-fab
            type="button">
      <mat-icon svgIcon="mat:cloud_download"></mat-icon>
    </button>
    
<table ... #matTable="matTable" #exporter="matTableExporter" 
[hiddenColumns]="excludedColumnsIndexesFromExport" (exportStarted)="exporting = true" (exportCompleted)="exporting = false">
<!-- SOME LOGIC HERE -->
</table>
```

   
In my TS class/component :
```
exportContentAsCsv(exporter: MatTableExporterDirective) {
      exporter.exportTable ('csv', {fileName: 'my_export_' + this.getDateTime (), delimiter: ";"})
  }
```

I don't remember exactly why I needed a custom exporter in the first place seeing my code now but most importantly it was accepted as the wanted solution, so it was it for me.

Hope this might helps you a bit or gives you a different idea to counter the original problem.

Good luck and happy coding !
