### ISSUE TITLE
"TypeError: Cannot read property 'componentView' of undefined at MatTableExporterDirective.push

### ISSUE THREAD

**Issue by ezouras** [HalitTalha/ng-material-extensions#25]
Here is the template:
<mat-table matTableExporter *ngIf="dataLoaded && !showMinTable" [dataSource]="allTableData" #exporter="matTableExporter" matSort>

The table wont load unless I remove the "matTableExporter"  and "#exporter="matTableExporter".  Otherwise the table is fine. 

The data being loaded for the table is in an ngOnInit method and once i have the data I have to conduct some manipulations before it's ready. the "dataLoaded" is not  set to true until all of this is complete.   I"m also using Angular 9rc3.  Here is the package.json:

"dependencies": {
    "@angular-devkit/build-angular": "^0.803.19",
    "@angular/animations": "^9.0.0-rc.3",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "^9.0.0-rc.3",
    "@angular/compiler": "^9.0.0-rc.3",
    "@angular/core": "^9.0.0-rc.3",
    "@angular/forms": "^9.0.0-rc.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "~8.2.3",
    "@angular/platform-browser": "^9.0.0-rc.3",
    "@angular/platform-browser-dynamic": "^9.0.0-rc.3",
    "cdk-table-exporter": "^1.2.2",
    "mat-table-exporter": "^1.2.2",
    "rxjs": "^6.0.0",
    "tslib": "^1.10.0",
    "zone.js": "^0.10.2"
  },

**Comment by HalitTalha** [comment]
Currently we are not supporting Angular 9 I hope we can soon.

**Comment by HalitTalha** [comment]
Forgot to close. Angular 9 is supported since 25998b147ffa5ddba68c87dffb2c4d2bf3571a24

`npm i mat-table-exporter` will install the latest version that's compatible with Angular 9
For Angular 6 - 8 you need to install `npm i mat-table-exporter@1.2.5`

**Comment by jellypop** [comment]
I'm using angular 9 and yet i get the same error

**Comment by HalitTalha** [comment]
Could you post your package.json?

**Comment by jellypop** [comment]
{
  "name": "locator-portal",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/cdk": "^9.2.3",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/material": "^8.2.1",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@ng-select/ng-select": "^4.0.0",
    "@syncfusion/ej2-angular-calendars": "^18.1.53",
    "@syncfusion/ej2-angular-dropdowns": "^18.1.53",
    "@syncfusion/ej2-dropdowns": "^18.1.53",
    "angular-highcharts": "^9.0.11",
    "angular-material": "^1.1.22",
    "bootstrap": "^4.4.1",
    "bootstrap-jquery": "^3.3.2",
    "highcharts": "^8.1.0",
    "highcharts-angular": "^2.4.0",
    "jquery": "^3.5.1",
    "mat-table-exporter": "^1.2.5",
    "ng-select": "^1.0.2",
    "rxjs": "~6.5.4",
    "ts-md5": "^1.2.7",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.3",
    "@angular/cli": "~9.0.3",
    "@angular/compiler-cli": "~9.0.2",
    "@angular/language-service": "~9.0.2",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }
}


> Could you post your package.json?

**Comment by HalitTalha** [comment]
> 
> 
> Forgot to close. Angular 9 is supported since [25998b1](https://github.com/HalitTalha/ng-material-extensions/commit/25998b147ffa5ddba68c87dffb2c4d2bf3571a24)
> 
> `npm i mat-table-exporter` will install the latest version that's compatible with Angular 9
> For Angular 6 - 8 you need to install `npm i mat-table-exporter@1.2.5`

Did you try out this. Because this error usually caused by an incompatibility between angular and mat-table-exporter versions.

**Comment by jellypop** [comment]
./node_modules/cdk-table-exporter/__ivy_ngcc__/fesm2015/cdk-table-exporter.js Module build failed: Error: ENOENT: no such file or directory
I got these errors after i updated mattableexporter

**Comment by HalitTalha** [comment]
Could you remove node modules completely and make an npm install?

**Comment by jellypop** [comment]
would that remove all my installed packages such as highcharts and others that i have installed?

**Comment by HalitTalha** [comment]
Yes if it is not suitable for you to download all that content then you can navigate in node_modules, find cdk-table-exporter folder and then remove it manually. Finally uninstall mat-table-exporter and then reinstall it.
