### ISSUE TITLE
Multiple footer rows export not working

### ISSUE THREAD

**Issue by ccosmincc** [HalitTalha/ng-material-extensions#50]
When having more then one footer row in a MatTable, only the first one gets exported. 
I wanted to give a try on solving it, but after building mat-table-exporter/cdk-table-exporter using the steps from 'Contribute' section, when trying to use the library in my app, I get the following error:

ERROR in Failed to compile entry-point mat-table-exporter (es2015 as esm2015) due to compilation errors:
../mat-table-ext/node_modules/@angular/material/table/table-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of MatTableExporterModule, but could not be resolved to an NgModule class

export declare class MatTableModule {

Any ideas on how to get the library working on my local environment, so I can try fixing the issue?

**Comment by HalitTalha** [comment]
Thanks for giving a hand. I'll try to reproduce as soon as I can.

**Comment by ccosmincc** [comment]
> Thanks for giving a hand. I'll try to reproduce as soon as I can.

Any updates regarding compilation issue?

**Comment by HalitTalha** [comment]
Sorry for being too late however it still seems like I will take care of this in the next release which I hope will be within 2 or 3 weeks.
