### ISSUE TITLE
 Cannot find module 'mat-table-exporter'.

### ISSUE THREAD

**Issue by gopukrishnanck** [HalitTalha/ng-material-extensions#62]
import { MatTableExporterModule } from 'mat-table-exporter';
Cannot find module 'mat-table-exporter'. can you please give an answer for this issue
while ng build i got this error
please help me to fix this

**Comment by HalitTalha** [comment]
Could you share your `app.module.ts` file?

**Comment by gopukrishnanck** [comment]
i just installed the package in server now issue solved thanks for this beautiful package loved it
