### ISSUE TITLE
Add UTF-8 BOM to CSV output

### ISSUE THREAD

**Issue by suzukieng** [HalitTalha/ng-material-extensions#63]
By default, the table exporter seems to output UTF-8 CSV data, but without a BOM (see: https://csv.thephpleague.com/8.0/bom/)

When opening the CSV file in Excel (yes, I realize there is an Excel export option, but unfortunately that is how many users consume CSV files), special characters will end up garbled by default. You can observe this behavior with your own example (row 10, Wilhelm Röntgen).

As a workaround, is it possible to intercept the output of the exporter, and patch the Blob (put a BOM in front of it), before sending it to the browser as download?

**Comment by HalitTalha** [comment]
Thanks for the feedback.
You can extend CsvExporter and use it as your custom exporter.
Check this stackblitz: https://stackblitz.com/edit/mte-cex-demo

For those who still use excel  version lower than 2013, there seems to be a known bug that makes the BOM ignored.

I'll label this as a bug later to be fixed.

**Comment by HalitTalha** [comment]
BOM is available by default
