### ISSUE TITLE
Ability to reset selectedRows

### ISSUE THREAD

**Issue by janakavishwajith** [HalitTalha/ng-material-extensions#67]
Hello There,
I wanted to clear selection after doing toggleRow on a table. 
Say, I selected 5 rows from original set of rows and do the export. Then I deselect all the rows and export again, but selection was not reset. It exports the selectedRows. 
But this can be easily enabled if you could add resetToggle() functionality setting selectedRows empty on CdkTableExporter project.
 
```
 resetToggle(): void {
     this._selectedRows = [];
   }

```
I tried to contribute for this, but this is a private repo.

Thanks,
Janaka.

**Comment by janakavishwajith** [comment]
Hello @HalitTalha ,
Any thoughts on above???

**Comment by HalitTalha** [comment]
Hello @janakavishwajith thanks for the effort.
Deselecting all rows should be working already. The example in https://halittalha.github.io/ng-material-extensions/ demonstrates it.
Could you post a stackblitz?

**Comment by janakavishwajith** [comment]
Hi @HalitTalha, 
Thanks for the response. 
Let me explain the situation,
User select 5 rows and export it as a CSV. What I am doing at that situation is, iterate through the list and call toggleRow(index: number) for those selected and export.
Then user deselect 2 rows from that and export, in that case I will iterate only 3 selected rows and call toggleRow(index: number) those three rows and what will happen actually deselected 2 rows will be exported. 
It would be great if there is a reset functionality, so I could call it before calling toggleRow. So, it will be an easy integration for any other usage too...
Hope you got me, if you want I will get a small stackblitz done for you. Existing one is too large and dependent for a standalone stackblitz.

Thanks..

**Comment by HalitTalha** [comment]
Hi @janakavishwajith,
Thanks for the clarification.
The thing is if you call the toggleRow in the selection `change `event instead of iterating through all the rows, you can achieve an effortless deselection mechanism. However thanks for your contribution. I'll accept and merge it for the next release.

**Comment by janakavishwajith** [comment]
Thanks @HalitTalha,
I'm happy to contribute more... :)
