### ISSUE TITLE
Export all data at once, instead of iterating through each page

### ISSUE THREAD

**Issue by aklauza** [HalitTalha/ng-material-extensions#76]
I have a big table with 10K rows and 10 cols. The page size is 10 rows. 

When using the exporter, it iterates page by page and takes forever to generate the excel file. **Is there a way to just call the exporter with `this.datasource.filteredData` to avoid looping and getting the export fast**? Thanks

**Comment by HalitTalha** [comment]
For huge datasets, you can also consider doing the export server side or else you can inject the appropriate exporter service and call the export method yourself. That way however you won't be able to benefit what cdkExporterDirective provides, like column hiding, being able to export the data as it's shown in html table.

```
constructor (public exporterService: XlsxExporterService)
...
this.exporterService.export(filteredData);
```

**Comment by aklauza** [comment]
The exporterService works. Thank you for your quick response Halit!

**Comment by jimmylevell** [comment]
As recommended I am using the this.exporterService.export approach instead of iterating through the pages. 
The export is working fine but somehow the export() cannot extract the table headers. So the resulting csv does not have a header row. 
Is there a way to provide the headers for the export?

**Comment by HalitTalha** [comment]
> 
> 
> As recommended I am using the this.exporterService.export approach instead of iterating through the pages.
> The export is working fine but somehow the export() cannot extract the table headers. So the resulting csv does not have a header row.
> Is there a way to provide the headers for the export?

ExporterService.export simply exports whatever you provide as your data. You can add your header row as the first object in your array.

**Comment by jimmylevell** [comment]
> > As recommended I am using the this.exporterService.export approach instead of iterating through the pages.
> > The export is working fine but somehow the export() cannot extract the table headers. So the resulting csv does not have a header row.
> > Is there a way to provide the headers for the export?
> 
> ExporterService.export simply exports whatever you provide as your data. You can add your header row as the first object in your array.

Thank you a lot for your reply! Working like charm! Thanks a lot!!
