### ISSUE TITLE
Option to export only the current page

### ISSUE THREAD

**Issue by diasandreotti** [HalitTalha/ng-material-extensions#80]
There is an option to export only the current page listed in the UI?

**Comment by HalitTalha** [comment]
This can be achieved by row selection.
Row selection is done by toggling the row indices that's to be exporter. `this.exporter.toggleRow(index)`
You can implement it by toggle on the rows at current page and off the old current page.

**Comment by diasandreotti** [comment]
Thanks, but so the exporter ends up going through the entire table to export only the desired lines. My question was whether there is a way to export only the current page, without the exporter alternating between all the pages.
