### ISSUE TITLE
NullInjectorError: StaticInjectorError on "ng build --prod" command to build angular app V8

### ISSUE THREAD

**Issue by Lubna842** [HalitTalha/ng-material-extensions#81]
Iam getting the following error while building angular app using --prod tag, otherwise it is working fine.
Angular: V8.

NullInjectorError: StaticInjectorError(l)[class{constructor(e,t){this._filterService=e,this._table=t,this.debounceTime=400,this.filterType=yy.ANYWHERE,this.caseSensitive=!1,this.initDebounceSubject()}ngDoCheck(){this._filterService.isChanged(this._oldExampleEntity,this.exampleEntity)&&(this._oldExampleEntity=this._filterService.toPlainJson(this.exampleEntity),this._exampleEntitySubject.next(void 0))}initDebounceSubject(){this._exampleEntitySubject=new ht(null),this._exampleEntitySubject.pipe(Ra(this.debounceTime)).subscribe(e=>{this.updateFilterPredicate()})}updateFilterPredicate(){const e=this.getMatDataSource();e&&(e.filterPredicate=this.getFilterPredicate(),e.filter=this.exampleEntity)}getFilterPredicate(){return this.customPredicate?this.customPredicate:e=>this._filterService.filterPredicate({example:this.exampleEntity,item:e},this.propertyOptions,{filterType:this.filterType,caseSensitive:this.caseSensitive})}getMatDataSource(){return this._table.dataSource}} -> e]: 
  StaticInjectorError(Platform: core)[class{constructor(e,t){this._filterService=e,this._table=t,this.debounceTime=400,this.filterType=yy.ANYWHERE,this.caseSensitive=!1,this.initDebounceSubject()}ngDoCheck(){this._filterService.isChanged(this._oldExampleEntity,this.exampleEntity)&&(this._oldExampleEntity=this._filterService.toPlainJson(this.exampleEntity),this._exampleEntitySubject.next(void 0))}initDebounceSubject(){this._exampleEntitySubject=new ht(null),this._exampleEntitySubject.pipe(Ra(this.debounceTime)).subscribe(e=>{this.updateFilterPredicate()})}updateFilterPredicate(){const e=this.getMatDataSource();e&&(e.filterPredicate=this.getFilterPredicate(),e.filter=this.exampleEntity)}getFilterPredicate(){return this.customPredicate?this.customPredicate:e=>this._filterService.filterPredicate({example:this.exampleEntity,item:e},this.propertyOptions,{filterType:this.filterType,caseSensitive:this.caseSensitive})}getMatDataSource(){return this._table.dataSource}} -> e]: 
    NullInjectorError: No provider for e!
    at te.get (http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:76609)
    at http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:89989
    at e (http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:90369)
    at Xe.get (http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:90520)
    at http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:89989
    at e (http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:90369)
    at Xe.get (http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:90520)
    at Xh (http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:197296)
    at Cp.get (http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:206054)
    at qp (http://127.0.0.1:8080/main-es2015.039d00438d69a07a2c65.js:1:209899)
Ol @ main-es2015.039d00438d69a07a2c65.js:1
handleError @ main-es2015.039d00438d69a07a2c65.js:1
(anonymous) @ main-es2015.039d00438d69a07a2c65.js:1
invoke @ polyfills-es2015.818dd14191713565ab15.js:1
run @ polyfills-es2015.818dd14191713565ab15.js:1
runOutsideAngular @ main-es2015.039d00438d69a07a2c65.js:1
tick @ main-es2015.039d00438d69a07a2c65.js:1
(anonymous) @ main-es2015.039d00438d69a07a2c65.js:1
invoke @ polyfills-es2015.818dd14191713565ab15.js:1
onInvoke @ main-es2015.039d00438d69a07a2c65.js:1
invoke @ polyfills-es2015.818dd14191713565ab15.js:1
run @ polyfills-es2015.818dd14191713565ab15.js:1
run @ main-es2015.039d00438d69a07a2c65.js:1
next @ main-es2015.039d00438d69a07a2c65.js:1
i @ main-es2015.039d00438d69a07a2c65.js:1
__tryOrUnsub @ main-es2015.039d00438d69a07a2c65.js:1
next @ main-es2015.039d00438d69a07a2c65.js:1
_next @ main-es2015.039d00438d69a07a2c65.js:1
next @ main-es2015.039d00438d69a07a2c65.js:1
next @ main-es2015.039d00438d69a07a2c65.js:1
emit @ main-es2015.039d00438d69a07a2c65.js:1
jg @ main-es2015.039d00438d69a07a2c65.js:1
onHasTask @ main-es2015.039d00438d69a07a2c65.js:1
hasTask @ polyfills-es2015.818dd14191713565ab15.js:1
_updateTaskCount @ polyfills-es2015.818dd14191713565ab15.js:1
_updateTaskCount @ polyfills-es2015.818dd14191713565ab15.js:1
runTask @ polyfills-es2015.818dd14191713565ab15.js:1
m @ polyfills-es2015.818dd14191713565ab15.js:1
invokeTask @ polyfills-es2015.818dd14191713565ab15.js:1
u @ polyfills-es2015.818dd14191713565ab15.js:1
p @ polyfills-es2015.818dd14191713565ab15.js:1

**Comment by HalitTalha** [comment]
Could you post your package.json?

**Comment by Lubna842** [comment]
{
  "name": "tomia-ui",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.1.0",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.1.0",
    "@angular/compiler": "~8.1.0",
    "@angular/core": "~8.1.0",
    "@angular/forms": "~8.1.0",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.1.0",
    "@angular/platform-browser-dynamic": "~8.1.0",
    "@angular/router": "~8.1.0",
    "@ng-idle/core": "^8.0.0-beta.4",
    "@ng-idle/keepalive": "^8.0.0-beta.4",
    "@types/lodash": "^4.14.161",
    "angular2-moment": "^1.9.0",
    "bootstrap": "^4.5.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.20",
    "mat-table-filter": "^1.2.5",
    "ngx-bootstrap": "^5.6.1",
    "ngx-loading": "^8.0.0",
    "ngx-spinner": "^8.1.0",
    "ngx-toastr": "^11.3.3",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "underscore": "^1.10.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.0",
    "@angular/cli": "~8.1.0",
    "@angular/compiler-cli": "~8.1.0",
    "@angular/language-service": "~8.1.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}

**Comment by HalitTalha** [comment]
Well, it is hard to pinpoint what's actually going wrong.
It could be the module that's imported with an incorrect path. Maybe you opted-in ivy?
If you don't mind please post the relevant ts and html files where you used mat-table-filter?

**Comment by Lubna842** [comment]
<div class="table-responsive" [hidden]="!dataSource.data.length">
<mat-table matTableFilter [exampleEntity]="filterEntity" [filterType]="filterType" [dataSource]="dataSource"
	class="mat-elevation-z8" flex layout="row" layout-fill>
	<ng-container matColumnDef="name">
		<mat-header-cell *matHeaderCellDef>
			<mat-form-field>
				<input matInput placeholder="Name" [(ngModel)]="filterEntity.name">
			</mat-form-field>
		</mat-header-cell>
		<mat-cell *matCellDef="let element"> {{element.name}} </mat-cell>
	</ng-container>

	<ng-container matColumnDef="id">
		<mat-header-cell *matHeaderCellDef>
			<mat-form-field>
				<input matInput placeholder="Id" [(ngModel)]="filterEntity.id">
			</mat-form-field>
		</mat-header-cell>
		<mat-cell *matCellDef="let element"> {{element.id}} </mat-cell>
	</ng-container>
 <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
 <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>
</div>



import { Component, OnInit} from '@angular/core';
import { Router } from '@angular/router';
import { myModel } from/model';
import { MatTableDataSource } from '@angular/material';
import { MatTableFilter } from 'mat-table-filter';

export class myComponent implements OnInit {
 
filterEntity: myModel;
filterType: MatTableFilter;
displayedColumns: string[] = ['name', 'id'];
dataSource:new MatTableDataSource<myModel>();
constructor() { }
ngOnInit() {
this.dataSource = new MatTableDataSource<myModel>();
this.filterEntity = new myModel();
this.filterType = MatTableFilter.ANYWHERE;
}  
}

**Comment by Lubna842** [comment]
<div class="table-responsive" [hidden]="!dataSource.data.length">
<mat-table matTableFilter [exampleEntity]="filterEntity" [filterType]="filterType" [dataSource]="dataSource"
	class="mat-elevation-z8" flex layout="row" layout-fill>
	<ng-container matColumnDef="name">
		<mat-header-cell *matHeaderCellDef>
			<mat-form-field>
				<input matInput placeholder="Name" [(ngModel)]="filterEntity.name">
			</mat-form-field>
		</mat-header-cell>
		<mat-cell *matCellDef="let element"> {{element.name}} </mat-cell>
	</ng-container>

	<ng-container matColumnDef="id">
		<mat-header-cell *matHeaderCellDef>
			<mat-form-field>
				<input matInput placeholder="Id" [(ngModel)]="filterEntity.id">
			</mat-form-field>
		</mat-header-cell>
		<mat-cell *matCellDef="let element"> {{element.id}} </mat-cell>
	</ng-container>
 <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
 <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>
</div>

**Comment by Lubna842** [comment]
<mat-table matTableFilter [exampleEntity]="filterEntity" [filterType]="filterType" [dataSource]="dataSource"
	class="mat-elevation-z8" flex layout="row" layout-fill>
	<ng-container matColumnDef="name">
		<mat-header-cell *matHeaderCellDef>
			<mat-form-field>
				<input matInput placeholder="Name" [(ngModel)]="filterEntity.name">
			</mat-form-field>
		</mat-header-cell>
		<mat-cell *matCellDef="let element"> {{element.name}} </mat-cell>
	</ng-container>
	</ng-container>
 <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
 <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>

**Comment by Lubna842** [comment]
import { Component, OnInit} from '@angular/core';
import { Router } from '@angular/router';
import { myModel } from/model';
import { MatTableDataSource } from '@angular/material';
import { MatTableFilter } from 'mat-table-filter';

export class myComponent implements OnInit {
 
filterEntity: myModel;
filterType: MatTableFilter;
displayedColumns: string[] = ['name', 'id'];
dataSource:new MatTableDataSource<myModel>();
constructor() { }
ngOnInit() {
this.dataSource = new MatTableDataSource<myModel>();
this.filterEntity = new myModel();
this.filterType = MatTableFilter.ANYWHERE;
}  
}

**Comment by zimejin** [comment]
I faced a similar issue and it was very difficult to debug. This helped me resolve it. I had to add the following dependencies in my app.module.ts file

`providers: [MatTableExporterDirective, ServiceLocatorService, DataExtractorService],`

[](https://stackoverflow.com/questions/55927857/nullinjectorerror-no-provider-for-t)
