### ISSUE TITLE
Hidden columns in table not exported

### ISSUE THREAD

**Issue by pantonis** [HalitTalha/ng-material-extensions#87]
I have a model with 10 properties. Only 8 are displayed in the mat table. However when I click export I want to export all 10 columns.
How can I achieve that?

**Comment by HalitTalha** [comment]
`mat-table-exporter` exports the table as it shows up in the page. If you want to export the datasource array instead, you can directly use the corresponding exporter service as explained [here](https://github.com/HalitTalha/ng-material-extensions/issues/76#issuecomment-664012818)
