### ISSUE TITLE
Dependency tree issue

### ISSUE THREAD

**Issue by annamj17** [HalitTalha/ng-material-extensions#92]
Hi,

I´m getting this error when trying to install mat-table exporter:

npm ERR! While resolving: my-app@0.0.0
npm ERR! Found: @angular/cdk@10.2.7
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^10.2.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^9.0.0" from mat-table-exporter@9.0.2
npm ERR! node_modules/mat-table-exporter
npm ERR!   mat-table-exporter@"*" from the root project

This is my package.json file

" "private": true,
  "dependencies": {
    "@angular/animations": "~10.2.0",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "~10.2.0",
    "@angular/compiler": "~10.2.0",
    "@angular/core": "~10.2.0",
    "@angular/forms": "~10.2.0",
    "@angular/material": "^10.2.7",
    "@angular/platform-browser": "~10.2.0",
    "@angular/platform-browser-dynamic": "~10.2.0",
    "@angular/router": "~10.2.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.0",
    "@angular/compiler-cli": "~10.2.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }"

Do I have to change the version of my cdk? And I am using Angular CLI

**Comment by pmcelreavy** [comment]
I have the same issue. To temporarily get around this you can add `--force` or `--legacy-peer-deps`. You'll also have to add that every time you run `npm update` until the dependencies on this library are updated.

**Comment by HalitTalha** [comment]
9.1.0 release had introduced a less strict peer dependency versioning.
