### ISSUE TITLE
util.js: ReferenceError: process is not defined

### ISSUE THREAD

**Issue by rwb196884** [HalitTalha/ng-material-extensions#95]
Been trying to install this package.

It seems to be necessary to add
```
    "lodash": "^4.17.15",
    "util": "0.12.3"
```
(Might like to add that to the docs?)

But it doesn't work.
![image](https://user-images.githubusercontent.com/12090617/101951133-65bbe500-3bee-11eb-9835-d612f3de024b.png)

Is there any chance that this package could ever work, or should I look elsewhere?

**Comment by HalitTalha** [comment]
We need more details to take that serious.
First, tell us which package you mean exporter or filter? If it is filter, it has a lodash dependency and it is not peer dep. So you dont have to bother with installing anything. And Lodash is not required for exporter.
We may need a bit more details like your package.json
